import * as Yup from "yup";
import { FULLNAME_REGEX, SIGNUP_SCHEMA_MESSAGES } from "./constants";
import {
  LOGIN_SCHEMA_MESSAGES,
  LOGIN_MIN_DETAILS,
  LOGIN_REGEX,
} from "../Login/constants";

export const SignUpSchema = Yup.object().shape({
  fullName: Yup.string()
    .matches(FULLNAME_REGEX, SIGNUP_SCHEMA_MESSAGES.VALID_NAME)
    .required(SIGNUP_SCHEMA_MESSAGES.NAME_REQUIRED),
  mobileNo: Yup.string()
    .test("len", LOGIN_SCHEMA_MESSAGES.MOBILE_NO_START_WITH_05, (val) =>
      val?.startsWith(LOGIN_MIN_DETAILS.NUMBER_STARTS_WITH)
    )
    .min(
      LOGIN_MIN_DETAILS.MINIMUM_USERNAME_LENGTH,
      LOGIN_SCHEMA_MESSAGES.MOBILE_NO_MIN_LENGTH
    )
    .matches(
      LOGIN_REGEX.MOBILE_NO_REGEX,
      LOGIN_SCHEMA_MESSAGES.MOBILE_NO_INVALID
    )
    .required(LOGIN_SCHEMA_MESSAGES.MOBILE_NO_REQUIRED),
  password: Yup.string()
    .matches(
      LOGIN_REGEX.LOWERCASE_REGEX,
      LOGIN_SCHEMA_MESSAGES.PASSWORD_RULES_LOWERCASE_ERROR_MSG
    )
    .matches(
      LOGIN_REGEX.UPPERCASE_REGEX,
      LOGIN_SCHEMA_MESSAGES.PASSWORD_RULES_UPPERCASE_ERROR_MSG
    )
    .matches(
      LOGIN_REGEX.NUMBER_REGEX,
      LOGIN_SCHEMA_MESSAGES.PASSWORD_RULES_NUMBER_ERROR_MSG
    )
    .matches(
      LOGIN_REGEX.SPECIAL_CHAR_REGEX,
      LOGIN_SCHEMA_MESSAGES.PASSWORD_RULES_SPECIAL_CHAR_ERROR_MSG
    )
    .min(
      LOGIN_MIN_DETAILS.MINIMUM_PASSWORD_LENGTH,
      LOGIN_SCHEMA_MESSAGES.PASSWORD_RULES_ERROR_MSG
    )
    .required(LOGIN_SCHEMA_MESSAGES.PASSWORD_REQUIRED),
  confirmPassword: Yup.string()
    .oneOf([Yup.ref("password")], SIGNUP_SCHEMA_MESSAGES.PASSWORD_NOT_MATCHED)
    .required(SIGNUP_SCHEMA_MESSAGES.CONFIRM_PASSWORD_REQUIRED),
});
